### ISSUE TITLE
top level statements

### ISSUE THREAD

**Issue by jbrucker** [touchtool/london-bike-sharing-system#1]
https://github.com/touchtool/london-bike-sharing-system/blob/09c0fe041df798b01b2f531faff5e45efd9fcf24/table/bicycle_dao.py#L5-L6

Any top-level statements you put in a python module are executed EACH TIME
the module is imported by other files.  Is that what you intend here?

**Comment by touchtool** [comment]
I was testing the code and didn't remove it for the test. For now, I delete that line of code and clean the code to make the code more understandable.
